
import { Workout } from '@/types/workout';

export const getRecommendedWorkouts = (
  bmi: number,
  age: number,
  goal: string
): Workout[] => {
  if (goal === 'lose') {
    if (bmi > 30) {
      // For obese individuals focusing on weight loss - Full week plan
      return [
        {
          title: 'Low Impact Cardio',
          description: 'Gentle cardio workout ideal for beginners and weight loss',
          duration: '30 min',
          difficulty: 'beginner',
          day: 'Monday',
          focus: 'Cardio',
          exercises: [
            { name: 'Walking in place', sets: 1, reps: '5 min', rest: '1 min', illustration: '/walking.svg', instructions: 'Stand tall with good posture. Lift your knees high and pump your arms naturally. Land softly on your feet.' },
            { name: 'Seated knee raises', sets: 3, reps: '12 reps', rest: '30 sec', illustration: '/knee-raise.svg', instructions: 'Sit on the edge of a chair with back straight. Engage your core and lift one knee toward your chest, then lower and repeat with the other leg.' },
            { name: 'Wall push-ups', sets: 3, reps: '10 reps', rest: '1 min', illustration: '/wall-pushup.svg', instructions: 'Stand facing a wall at arm\'s length. Place hands on the wall at shoulder height, shoulder-width apart. Bend elbows to bring chest toward the wall, then push back.' },
            { name: 'Seated leg extensions', sets: 3, reps: '15 reps', rest: '1 min', illustration: '/leg-extension.svg', instructions: 'Sit on a chair with feet flat on the floor. Straighten one leg until parallel to the floor, hold briefly, then lower. Repeat with the other leg.' },
            { name: 'Arm circles', sets: 2, reps: '30 sec', rest: '30 sec', illustration: '/arm-circles.svg', instructions: 'Stand with feet shoulder-width apart. Extend arms to the sides and make small circular motions, gradually increasing the size of circles.' },
          ],
        },
        {
          title: 'Upper Body Strength',
          description: 'Gentle upper body workout for beginners',
          duration: '25 min',
          difficulty: 'beginner',
          day: 'Tuesday',
          focus: 'Upper Body',
          exercises: [
            { name: 'Wall push-ups', sets: 3, reps: '10 reps', rest: '45 sec', illustration: '/wall-pushup.svg', instructions: 'Stand facing a wall at arm\'s length. Place hands on the wall at shoulder height, shoulder-width apart. Bend elbows to bring chest toward the wall, then push back.' },
            { name: 'Seated shoulder press', sets: 3, reps: '12 reps', rest: '45 sec', illustration: '/seated-press.svg', instructions: 'Sit with back supported, holding light weights at shoulder height. Press weights overhead until arms are extended (not locked), then lower back to shoulders.' },
            { name: 'Upright rows', sets: 3, reps: '12 reps', rest: '45 sec', illustration: '/upright-row.svg', instructions: 'Stand holding light weights in front of thighs. Lift weights vertically close to body until elbows are at shoulder height, then lower slowly.' },
            { name: 'Seated bicep curls', sets: 3, reps: '12 reps', rest: '45 sec', illustration: '/bicep-curl.svg', instructions: 'Sit with back supported, arms extended down. Curl weights toward shoulders while keeping elbows close to sides, then lower slowly.' },
            { name: 'Tricep extensions', sets: 3, reps: '12 reps', rest: '45 sec', illustration: '/tricep-extension.svg', instructions: 'Sit holding one light weight with both hands. Raise weight overhead, lower it behind head by bending elbows, then extend arms back up.' },
          ],
        },
        {
          title: 'Rest Day Activities',
          description: 'Light stretching and recovery',
          duration: '20 min',
          difficulty: 'beginner',
          day: 'Wednesday',
          focus: 'Recovery',
          exercises: [
            { name: 'Gentle walking', sets: 1, reps: '10 min', rest: '0 min', illustration: '/walking.svg', instructions: 'Walk at a comfortable pace focusing on good posture and deep breathing. This is not meant to be intense.' },
            { name: 'Neck stretches', sets: 2, reps: '30 sec each direction', rest: '15 sec', illustration: '/neck-stretch.svg', instructions: 'Gently tilt head to one side, bringing ear toward shoulder until you feel a stretch. Hold, then repeat on other side and forward/back.' },
            { name: 'Shoulder rolls', sets: 2, reps: '10 each way', rest: '15 sec', illustration: '/shoulder-rolls.svg', instructions: 'Roll shoulders forward in circular motion, then backward. Keep movements slow and controlled.' },
            { name: 'Seated hamstring stretch', sets: 2, reps: '30 sec each leg', rest: '15 sec', illustration: '/hamstring-stretch.svg', instructions: 'Sit with one leg extended, other foot against inner thigh. Reach toward extended foot until you feel a stretch, hold.' },
            { name: 'Deep breathing', sets: 1, reps: '5 min', rest: '0 min', illustration: '/breathing.svg', instructions: 'Sit comfortably with good posture. Breathe deeply through nose, expanding belly. Hold briefly, then exhale slowly through mouth.' },
          ],
        },
        {
          title: 'Lower Body Focus',
          description: 'Gentle lower body strengthening workout',
          duration: '30 min',
          difficulty: 'beginner',
          day: 'Thursday',
          focus: 'Lower Body',
          exercises: [
            { name: 'Chair sits', sets: 3, reps: '10 reps', rest: '45 sec', illustration: '/chair-sit.svg', instructions: 'Stand in front of chair with feet shoulder-width apart. Lower hips toward chair stopping just before sitting, then stand back up.' },
            { name: 'Calf raises with support', sets: 3, reps: '15 reps', rest: '30 sec', illustration: '/calf-raise.svg', instructions: 'Stand holding onto chair or wall for balance. Raise heels off floor until standing on balls of feet, hold briefly, then lower.' },
            { name: 'Seated leg extensions', sets: 3, reps: '12 each leg', rest: '45 sec', illustration: '/leg-extension.svg', instructions: 'Sit on chair with good posture. Extend one leg until straight, hold briefly at top, then lower. Repeat with other leg.' },
            { name: 'Glute bridges', sets: 3, reps: '12 reps', rest: '45 sec', illustration: '/glute-bridge.svg', instructions: 'Lie on back with knees bent, feet flat. Press through heels to lift hips toward ceiling until body forms straight line from shoulders to knees.' },
            { name: 'Inner thigh lifts', sets: 3, reps: '12 each side', rest: '30 sec', illustration: '/inner-thigh.svg', instructions: 'Lie on side with bottom leg bent for support. Keep top leg straight, raise it upward, hold briefly, then lower. Switch sides.' },
          ],
        },
        {
          title: 'Gentle Mobility',
          description: 'Improve range of motion and joint health',
          duration: '25 min',
          difficulty: 'beginner',
          day: 'Friday',
          focus: 'Mobility',
          exercises: [
            { name: 'Shoulder rolls', sets: 2, reps: '10 each way', rest: '30 sec', illustration: '/shoulder-rolls.svg', instructions: 'Stand with feet shoulder-width apart. Roll shoulders forward in a circular motion, then backward. Keep movements slow and controlled.' },
            { name: 'Standing side bends', sets: 3, reps: '8 each side', rest: '30 sec', illustration: '/side-bends.svg', instructions: 'Stand with feet shoulder-width apart. Place one hand on hip and extend the other overhead. Bend sideways toward the side with hand on hip, then return to center.' },
            { name: 'Seated hamstring stretch', sets: 2, reps: '30 sec hold', rest: '15 sec', illustration: '/hamstring-stretch.svg', instructions: 'Sit on the edge of a chair with one leg extended, heel on floor. Hinge at hips to lean forward until you feel a stretch in the back of the extended leg.' },
            { name: 'Ankle rotations', sets: 2, reps: '10 each way', rest: '30 sec', illustration: '/ankle-rotation.svg', instructions: 'Sit on a chair and lift one foot off the ground. Rotate ankle in a circular motion clockwise, then counterclockwise. Repeat with other foot.' },
            { name: 'Neck stretches', sets: 2, reps: '15 sec each direction', rest: '15 sec', illustration: '/neck-stretch.svg', instructions: 'Sit or stand with good posture. Gently tilt head to one side, bringing ear toward shoulder until you feel a stretch. Hold, then repeat on other side.' },
          ],
        },
        {
          title: 'Balance & Stability',
          description: 'Improve balance and core stability',
          duration: '25 min',
          difficulty: 'beginner',
          day: 'Saturday',
          focus: 'Balance/Core',
          exercises: [
            { name: 'Supported single leg stand', sets: 3, reps: '30 sec each leg', rest: '30 sec', illustration: '/single-leg.svg', instructions: 'Stand next to chair or wall for support. Lift one foot slightly off ground and balance, using support as needed. Switch legs.' },
            { name: 'Seated marches', sets: 3, reps: '20 total', rest: '30 sec', illustration: '/seated-march.svg', instructions: 'Sit with good posture at edge of chair. Alternately lift knees toward chest in marching motion while maintaining balance.' },
            { name: 'Wall plank', sets: 3, reps: '20 sec', rest: '30 sec', illustration: '/wall-plank.svg', instructions: 'Stand facing wall at arm\'s length. Place forearms on wall at shoulder height and engage core as if doing a standing plank.' },
            { name: 'Seated twist', sets: 2, reps: '10 each side', rest: '30 sec', illustration: '/seated-twist.svg', instructions: 'Sit with good posture, feet flat. Place hands on opposite shoulders, rotate upper body to one side, hold briefly, then other side.' },
            { name: 'Heel-to-toe walk', sets: 2, reps: '10 steps each way', rest: '30 sec', illustration: '/heel-toe.svg', instructions: 'Walk in straight line placing heel of one foot directly in front of toes of other foot. Use wall or chair for support if needed.' },
          ],
        },
        {
          title: 'Active Recovery',
          description: 'Light activity to promote circulation and recovery',
          duration: '20 min',
          difficulty: 'beginner',
          day: 'Sunday',
          focus: 'Recovery',
          exercises: [
            { name: 'Gentle walking', sets: 1, reps: '10 min', rest: '0 min', illustration: '/walking.svg', instructions: 'Walk at a comfortable pace indoors or outdoors. Focus on good posture and deep breathing.' },
            { name: 'Full body stretch', sets: 1, reps: '30 sec each position', rest: '0 min', illustration: '/full-stretch.svg', instructions: 'Perform a series of gentle stretches for major muscle groups. Hold each stretch without bouncing.' },
            { name: 'Deep breathing', sets: 3, reps: '5 breaths', rest: '30 sec', illustration: '/breathing.svg', instructions: 'Sit comfortably with good posture. Inhale deeply through nose for 4 counts, hold briefly, exhale slowly through mouth for 6 counts.' },
            { name: 'Self-massage', sets: 1, reps: '1-2 min per area', rest: '0 min', illustration: '/self-massage.svg', instructions: 'Use hands or foam roller to gently massage sore muscles, focusing on areas that feel tight.' },
            { name: 'Visualization', sets: 1, reps: '3 min', rest: '0 min', illustration: '/visualization.svg', instructions: 'Close eyes and visualize successful workouts and achieving fitness goals. Practice positive self-talk.' },
          ],
        },
      ];
    } else {
      // For overweight or normal weight individuals focusing on weight loss - Full week plan
      return [
        {
          title: 'HIIT Fat Burner',
          description: 'High intensity intervals to maximize calorie burn',
          duration: '25 min',
          difficulty: 'intermediate',
          day: 'Monday',
          focus: 'Cardio',
          exercises: [
            { name: 'Jumping jacks', sets: 3, reps: '30 sec', rest: '15 sec', illustration: '/jumping-jacks.svg', instructions: 'Start standing with arms at sides and feet together. Jump while raising arms and separating legs to sides. Return to starting position and repeat quickly.' },
            { name: 'Mountain climbers', sets: 3, reps: '30 sec', rest: '15 sec', illustration: '/mountain-climbers.svg', instructions: 'Start in plank position with arms straight. Rapidly alternate bringing knees to chest, keeping your back flat and hips level throughout.' },
            { name: 'Burpees', sets: 3, reps: '30 sec', rest: '30 sec', illustration: '/burpees.svg', instructions: 'Begin standing, drop to a squat position, kick feet back to plank, perform a push-up, jump feet forward to squat, then explode upward with a jump.' },
            { name: 'High knees', sets: 3, reps: '30 sec', rest: '15 sec', illustration: '/high-knees.svg', instructions: 'Stand in place, rapidly drive knees toward chest alternating legs. Keep your core engaged and maintain an upright posture.' },
            { name: 'Plank jacks', sets: 3, reps: '30 sec', rest: '30 sec', illustration: '/plank-jacks.svg', instructions: 'Begin in plank position. Jump both feet outward like a jumping jack, then jump them back together. Keep your core tight and maintain a straight body position.' },
          ],
        },
        {
          title: 'Chest & Triceps Day',
          description: 'Build upper body pushing muscles',
          duration: '40 min',
          difficulty: 'intermediate',
          day: 'Tuesday',
          focus: 'Chest/Triceps',
          exercises: [
            { name: 'Push-ups', sets: 4, reps: '10-15 reps', rest: '60 sec', equipment: 'Bodyweight', illustration: '/push-ups.svg', instructions: 'Start in plank position with hands slightly wider than shoulders. Lower body until chest nearly touches floor, then push back up. Keep body straight.' },
            { name: 'Incline push-ups', sets: 3, reps: '12-15 reps', rest: '45 sec', equipment: 'Bench/Chair', illustration: '/incline-pushup.svg', instructions: 'Place hands on elevated surface, shoulder-width apart. Lower chest toward surface with body straight, then push back up.' },
            { name: 'Tricep dips', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Chair/Bench', illustration: '/tricep-dips.svg', instructions: 'Sit on edge of chair, hands gripping edge. Slide forward so rear is off seat, lower body by bending elbows, then push back up.' },
            { name: 'Diamond push-ups', sets: 3, reps: '10 reps', rest: '60 sec', equipment: 'Bodyweight', illustration: '/diamond-pushup.svg', instructions: 'Form diamond shape with hands under chest in push-up position. Lower body with elbows close to sides, then push back up.' },
            { name: 'Chest flies', sets: 3, reps: '15 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/chest-flies.svg', instructions: 'Lie on back holding dumbbells above chest with slight elbow bend. Lower arms out to sides in arc motion, then bring back together.' },
          ],
        },
        {
          title: 'Back & Biceps Day',
          description: 'Develop back width and arm strength',
          duration: '40 min',
          difficulty: 'intermediate',
          day: 'Wednesday',
          focus: 'Back/Biceps',
          exercises: [
            { name: 'Dumbbell rows', sets: 4, reps: '12 each arm', rest: '45 sec', equipment: 'Dumbbells', illustration: '/dumbbell-rows.svg', instructions: 'Place one knee and hand on bench, other foot on floor. With dumbbell in free hand, pull weight up to side of chest, keeping elbow close to body.' },
            { name: 'Resistance band pulls', sets: 3, reps: '15 reps', rest: '45 sec', equipment: 'Resistance Band', illustration: '/band-pulls.svg', instructions: 'Hold band in front with hands shoulder-width apart. Pull band apart by squeezing shoulder blades together, then slowly return.' },
            { name: 'Bodyweight rows', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Table/Bar', illustration: '/bodyweight-rows.svg', instructions: 'Position yourself under table/bar, gripping edge. Pull chest toward edge with body straight, then lower with control.' },
            { name: 'Bicep curls', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/bicep-curls.svg', instructions: 'Stand with dumbbells at sides, palms forward. Curl weights toward shoulders while keeping elbows stationary, then lower with control.' },
            { name: 'Hammer curls', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/hammer-curls.svg', instructions: 'Stand with dumbbells at sides, palms facing inward. Curl weights toward shoulders maintaining neutral grip, then lower with control.' },
          ],
        },
        {
          title: 'Active Recovery',
          description: 'Light cardio and stretching for recovery',
          duration: '30 min',
          difficulty: 'beginner',
          day: 'Thursday',
          focus: 'Recovery',
          exercises: [
            { name: 'Brisk walking', sets: 1, reps: '10 min', rest: '0 min', illustration: '/walking.svg', instructions: 'Walk at a comfortable but brisk pace. Focus on good posture and controlled breathing.' },
            { name: 'Dynamic stretching', sets: 2, reps: '30 sec each movement', rest: '15 sec', illustration: '/dynamic-stretch.svg', instructions: 'Perform arm circles, leg swings, torso twists and other gentle movements to increase blood flow to muscles.' },
            { name: 'Foam rolling', sets: 1, reps: '60 sec per area', rest: '0 min', equipment: 'Foam Roller', illustration: '/foam-roll.svg', instructions: 'Roll major muscle groups (quads, hamstrings, calves, back) slowly over foam roller. Pause on tight spots for 10-30 seconds.' },
            { name: 'Cat-cow stretch', sets: 3, reps: '8 cycles', rest: '30 sec', illustration: '/cat-cow.svg', instructions: 'Start on hands and knees. Alternate between arching back upward (cat) and letting it drop while lifting head (cow).' },
            { name: 'Child\'s pose', sets: 3, reps: '30 sec hold', rest: '15 sec', illustration: '/child-pose.svg', instructions: 'Kneel with toes together, knees apart. Extend arms forward while sitting back toward heels, lowering forehead to mat.' },
          ],
        },
        {
          title: 'Lower Body Sculpt',
          description: 'Focus on legs and glutes for strength and definition',
          duration: '35 min',
          difficulty: 'intermediate',
          day: 'Friday',
          focus: 'Lower Body',
          exercises: [
            { name: 'Squats', sets: 4, reps: '15 reps', rest: '45 sec', equipment: 'Bodyweight', illustration: '/squats.svg', instructions: 'Stand with feet shoulder-width apart. Bend knees and lower hips as if sitting in chair, keeping chest up and knees behind toes, then return to standing.' },
            { name: 'Alternating lunges', sets: 3, reps: '12 each leg', rest: '45 sec', equipment: 'Bodyweight', illustration: '/lunges.svg', instructions: 'Stand tall, step forward with one leg and lower until both knees are bent at 90 degrees. Push through front heel to return to standing, then repeat with other leg.' },
            { name: 'Glute bridges', sets: 3, reps: '15 reps', rest: '30 sec', equipment: 'Bodyweight', illustration: '/glute-bridge.svg', instructions: 'Lie on back with knees bent, feet flat on floor. Press through heels to lift hips toward ceiling until body forms straight line from shoulders to knees, then lower.' },
            { name: 'Calf raises', sets: 3, reps: '20 reps', rest: '30 sec', equipment: 'Bodyweight', illustration: '/calf-raises.svg', instructions: 'Stand with feet hip-width apart. Rise onto balls of feet by lifting heels off ground, pause at top, then lower heels back down.' },
            { name: 'Side lunges', sets: 3, reps: '10 each side', rest: '45 sec', equipment: 'Bodyweight', illustration: '/side-lunges.svg', instructions: 'Stand with feet together. Step wide to one side, bend that knee while keeping other leg straight. Push off bent leg to return to center, then repeat on other side.' },
          ],
        },
        {
          title: 'Shoulders & Core Day',
          description: 'Build shoulder definition and core strength',
          duration: '35 min',
          difficulty: 'intermediate',
          day: 'Saturday',
          focus: 'Shoulders/Core',
          exercises: [
            { name: 'Shoulder press', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/shoulder-press.svg', instructions: 'Stand or sit holding dumbbells at shoulder height. Press weights overhead until arms almost fully extend (slight bend at top), then lower.' },
            { name: 'Lateral raises', sets: 3, reps: '15 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/lateral-raises.svg', instructions: 'Stand with dumbbells at sides. With slight elbow bend, raise arms out to sides until parallel with floor, then lower slowly.' },
            { name: 'Front raises', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/front-raise.svg', instructions: 'Stand with dumbbells in front of thighs. Raise one arm forward to shoulder height with palm down, lower and alternate sides.' },
            { name: 'Plank', sets: 3, reps: '45 sec', rest: '30 sec', equipment: 'Bodyweight', illustration: '/plank.svg', instructions: 'Position forearms on ground with elbows under shoulders. Create straight line from head to heels, engage core and hold position.' },
            { name: 'Russian twists', sets: 3, reps: '15 each side', rest: '30 sec', equipment: 'Bodyweight/Dumbbell', illustration: '/russian-twist.svg', instructions: 'Sit with knees bent, feet lifted slightly. Lean back to engage core, rotate torso to tap hands on floor beside hips, alternating sides.' },
          ],
        },
        {
          title: 'Sunday Fun Run',
          description: 'Steady state cardio for endurance',
          duration: '30-45 min',
          difficulty: 'intermediate',
          day: 'Sunday',
          focus: 'Cardio',
          exercises: [
            { name: 'Warm-up', sets: 1, reps: '5 min', rest: '0 min', illustration: '/warm-up.svg', instructions: 'Start with light walking or marching in place. Focus on warming up major muscle groups with gentle movement.' },
            { name: 'Steady jogging/running', sets: 1, reps: '20-30 min', rest: '0 min', illustration: '/jogging.svg', instructions: 'Maintain a consistent, comfortable pace where you can still hold a conversation. Focus on breathing rhythm and good form.' },
            { name: 'Walking intervals', sets: 3, reps: '1 min', rest: '4 min jogging', illustration: '/walking.svg', instructions: 'Alternate between jogging and walking if needed. Use walking as active recovery between jogging intervals.' },
            { name: 'Cool down walk', sets: 1, reps: '5 min', rest: '0 min', illustration: '/cooldown.svg', instructions: 'Gradually reduce intensity with slower walking. Allow heart rate to decrease gradually toward resting level.' },
            { name: 'Post-run stretching', sets: 1, reps: '30 sec each stretch', rest: '0 min', illustration: '/stretching.svg', instructions: 'Focus on stretching calves, hamstrings, quads, and hip flexors. Hold each stretch without bouncing.' },
          ],
        },
      ];
    }
  } else if (goal === 'gain') {
    // For individuals focusing on muscle gain with full week day splits
    return [
      {
        title: 'Chest & Triceps',
        description: 'Focus on building upper body pushing muscles',
        duration: '45 min',
        difficulty: 'advanced',
        day: 'Monday',
        focus: 'Chest/Triceps',
        exercises: [
          { name: 'Bench press', sets: 4, reps: '8-10 reps', rest: '90 sec', equipment: 'Barbell/Bench', illustration: '/bench-press.svg', instructions: 'Lie on bench with feet flat on floor. Grip barbell slightly wider than shoulders, lower to chest with control, then press back up until arms are extended.' },
          { name: 'Incline dumbbell press', sets: 4, reps: '10 reps', rest: '90 sec', equipment: 'Dumbbells/Bench', illustration: '/incline-press.svg', instructions: 'Set bench to 30-45 degree angle. Hold dumbbells at shoulder level, press up until arms extend fully, then lower with control until slight stretch is felt in chest.' },
          { name: 'Chest dips', sets: 3, reps: '8-12 reps', rest: '90 sec', equipment: 'Dip bars', illustration: '/chest-dips.svg', instructions: 'Hold yourself up on dip bars. Lean forward slightly, lower body by bending arms until you feel stretch in chest, then push back up to starting position.' },
          { name: 'Skull crushers', sets: 3, reps: '10-12 reps', rest: '60 sec', equipment: 'EZ bar/Dumbbells', illustration: '/skull-crushers.svg', instructions: 'Lie on bench holding weight(s) above chest with arms extended. Keeping upper arms stationary, bend at elbows to lower weight toward forehead, then extend arms back up.' },
          { name: 'Cable tricep pushdowns', sets: 3, reps: '12-15 reps', rest: '45 sec', equipment: 'Cable Machine', illustration: '/tricep-pushdown.svg', instructions: 'Stand facing cable machine with rope/bar attachment at chest height. Grip attachment, keep elbows at sides, extend arms downward until fully straight, then control return.' },
        ],
      },
      {
        title: 'Back & Biceps',
        description: 'Develop width, thickness and pulling strength',
        duration: '50 min',
        difficulty: 'advanced',
        day: 'Tuesday',
        focus: 'Back/Biceps',
        exercises: [
          { name: 'Deadlifts', sets: 4, reps: '6-8 reps', rest: '120 sec', equipment: 'Barbell', illustration: '/deadlift.svg', instructions: 'Stand with feet hip-width apart, barbell over mid-foot. Hinge at hips, grip bar outside knees, lift by driving through heels while keeping back straight.' },
          { name: 'Bent over rows', sets: 4, reps: '8-10 reps', rest: '90 sec', equipment: 'Barbell', illustration: '/bent-over-row.svg', instructions: 'Hinge at hips with slight knee bend, back flat and nearly parallel to floor. Pull barbell to lower chest/upper abs, squeezing shoulder blades, then lower with control.' },
          { name: 'Lat pulldowns', sets: 4, reps: '10-12 reps', rest: '60 sec', equipment: 'Cable Machine', illustration: '/lat-pulldown.svg', instructions: 'Sit at machine with thighs secured. Grip bar wider than shoulders, pull down to upper chest while leaning slightly back, then control return to starting position.' },
          { name: 'Barbell curls', sets: 3, reps: '10-12 reps', rest: '60 sec', equipment: 'Barbell', illustration: '/barbell-curl.svg', instructions: 'Stand with feet shoulder-width apart, holding barbell with underhand grip. Keeping upper arms stationary, curl weight toward shoulders, then lower with control.' },
          { name: 'Hammer curls', sets: 3, reps: '12 each arm', rest: '60 sec', equipment: 'Dumbbells', illustration: '/hammer-curl.svg', instructions: 'Stand holding dumbbells with palms facing each other. Curl weights toward shoulders while maintaining neutral grip (thumbs up), then lower with control.' },
        ],
      },
      {
        title: 'Rest & Recovery',
        description: 'Active recovery to promote muscle repair',
        duration: '30 min',
        difficulty: 'beginner',
        day: 'Wednesday',
        focus: 'Recovery',
        exercises: [
          { name: 'Light cardio', sets: 1, reps: '10 min', rest: '0 min', illustration: '/light-cardio.svg', instructions: 'Choose light cardio like walking, slow cycling, or elliptical at an easy pace. Keep heart rate between 110-120 bpm.' },
          { name: 'Foam rolling', sets: 1, reps: '60 sec per area', rest: '0 min', equipment: 'Foam Roller', illustration: '/foam-roll.svg', instructions: 'Roll major muscle groups worked in previous days (chest, back, arms). Move slowly, pause on tight spots for 10-30 seconds.' },
          { name: 'Static stretching', sets: 2, reps: '30 sec per stretch', rest: '0 min', illustration: '/stretching.svg', instructions: 'Perform static stretches for chest, back, biceps, triceps. Hold each stretch at point of mild tension without bouncing.' },
          { name: 'Light band work', sets: 2, reps: '20 reps', rest: '30 sec', equipment: 'Resistance Band', illustration: '/band-work.svg', instructions: 'Use very light resistance bands for rotator cuff exercises and mobility work. Focus on smooth movement patterns, not resistance.' },
          { name: 'Hydration & nutrition focus', sets: 1, reps: 'Throughout day', rest: '0 min', illustration: '/hydration.svg', instructions: 'Ensure adequate water intake (aim for 3-4 liters) and focus on protein/carb intake for recovery. Consider branch chain amino acids.' },
        ],
      },
      {
        title: 'Legs & Core',
        description: 'Build lower body strength and stability',
        duration: '55 min',
        difficulty: 'advanced',
        day: 'Thursday',
        focus: 'Legs/Core',
        exercises: [
          { name: 'Barbell squats', sets: 4, reps: '8-10 reps', rest: '90 sec', equipment: 'Barbell', illustration: '/barbell-squat.svg', instructions: 'Place bar across upper back, feet shoulder-width apart. Bend knees and hips to lower until thighs are parallel to floor or lower, then push through heels to stand.' },
          { name: 'Romanian deadlifts', sets: 4, reps: '8-10 reps', rest: '90 sec', equipment: 'Barbell', illustration: '/romanian-deadlift.svg', instructions: 'Stand holding barbell at hip level. Hinge at hips while maintaining slight knee bend, lower bar along legs until stretch in hamstrings, then drive hips forward to return.' },
          { name: 'Leg press', sets: 3, reps: '10-12 reps', rest: '90 sec', equipment: 'Machine', illustration: '/leg-press.svg', instructions: 'Sit in machine with feet shoulder-width on platform. Release safety, lower weight by bending knees toward chest without lifting hips, then press back to start position.' },
          { name: 'Hanging leg raises', sets: 3, reps: '10-15 reps', rest: '60 sec', equipment: 'Pull-up Bar', illustration: '/hanging-leg-raise.svg', instructions: 'Hang from pull-up bar with arms straight. Keeping legs straight or slightly bent, raise them until parallel to floor or higher, then lower with control.' },
          { name: 'Cable woodchoppers', sets: 3, reps: '12 each side', rest: '45 sec', equipment: 'Cable Machine', illustration: '/woodchopper.svg', instructions: 'Set cable at high position, stand with side to machine. Grab handle with both hands, pull down and across body in diagonal chopping motion, then control return.' },
        ],
      },
      {
        title: 'Shoulders & Arms',
        description: 'Develop well-rounded shoulder and arm development',
        duration: '45 min',
        difficulty: 'advanced',
        day: 'Friday',
        focus: 'Shoulders/Arms',
        exercises: [
          { name: 'Military Press', sets: 4, reps: '8 reps', rest: '90 sec', equipment: 'Barbell', illustration: '/military-press.svg', instructions: 'Stand or sit with barbell at shoulder height. Press weight overhead until arms are fully extended, then lower with control back to shoulders.' },
          { name: 'Lateral raises', sets: 3, reps: '15 reps', rest: '45 sec', equipment: 'Dumbbells', illustration: '/lateral-raise.svg', instructions: 'Stand with dumbbells at sides, palms facing inward. Keeping slight bend in elbows, raise arms out to sides until parallel with floor, then slowly lower.' },
          { name: 'Face pulls', sets: 3, reps: '15 reps', rest: '60 sec', equipment: 'Cable Machine', illustration: '/face-pull.svg', instructions: 'Set cable at eye level with rope attachment. Pull rope toward face with elbows high, focusing on pulling shoulder blades together, then return slowly.' },
          { name: 'EZ bar curls', sets: 3, reps: '10-12 reps', rest: '45 sec', equipment: 'EZ Curl Bar', illustration: '/ez-curl.svg', instructions: 'Stand holding EZ bar with underhand grip. Curl weight toward shoulders while keeping elbows stationary, then lower with control.' },
          { name: 'Overhead tricep extension', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Dumbbell', illustration: '/overhead-extension.svg', instructions: 'Hold dumbbell with both hands above head, arms extended. Bend elbows to lower weight behind head, keeping upper arms stationary, then extend arms to raise weight.' },
        ],
      },
      {
        title: 'Weak Points Focus',
        description: 'Target lagging muscle groups for balanced physique',
        duration: '40 min',
        difficulty: 'advanced',
        day: 'Saturday',
        focus: 'Custom',
        exercises: [
          { name: 'Custom exercise 1', sets: 4, reps: '8-12 reps', rest: '60 sec', equipment: 'Various', illustration: '/custom-ex1.svg', instructions: 'Select an exercise targeting your weakest muscle group. Focus on proper form and moderate weight for quality contractions.' },
          { name: 'Custom exercise 2', sets: 4, reps: '8-12 reps', rest: '60 sec', equipment: 'Various', illustration: '/custom-ex2.svg', instructions: 'Choose a second exercise for your lagging muscle group, preferably with a different angle or movement pattern than the first.' },
          { name: 'Isolation movement', sets: 3, reps: '12-15 reps', rest: '45 sec', equipment: 'Various', illustration: '/isolation.svg', instructions: 'Select an isolation exercise for precise targeting of weak point. Focus on mind-muscle connection and controlled movement.' },
          { name: 'Core stabilization', sets: 3, reps: '45 sec', rest: '30 sec', equipment: 'Bodyweight', illustration: '/core-stab.svg', instructions: 'Choose from plank variations, stability ball exercises, or anti-rotation movements to improve core strength.' },
          { name: 'Mobility work', sets: 2, reps: '30 sec per movement', rest: '15 sec', equipment: 'Bodyweight', illustration: '/mobility.svg', instructions: 'Perform mobility exercises for any tight areas related to your weak points. Focus on increasing range of motion and tissue quality.' },
        ],
      },
      {
        title: 'Complete Rest Day',
        description: 'Full recovery day to maximize muscle growth',
        duration: '0 min (passive recovery)',
        difficulty: 'beginner',
        day: 'Sunday',
        focus: 'Recovery',
        exercises: [
          { name: 'Complete rest', sets: 0, reps: '0', rest: '0', illustration: '/rest.svg', instructions: 'Take a complete day off from structured exercise. Allow your body to recover fully and muscles to repair and grow.' },
          { name: 'Proper nutrition', sets: 0, reps: '0', rest: '0', illustration: '/nutrition.svg', instructions: 'Focus on maintaining caloric surplus with emphasis on protein intake. Aim for 1.6-2.2g protein per kg of bodyweight.' },
          { name: 'Hydration', sets: 0, reps: '0', rest: '0', illustration: '/hydration.svg', instructions: 'Ensure adequate water intake throughout the day. Well-hydrated muscles recover more efficiently.' },
          { name: 'Sleep optimization', sets: 0, reps: '0', rest: '0', illustration: '/sleep.svg', instructions: 'Prioritize 7-9 hours of quality sleep. Consider blackout curtains, consistent sleep schedule, and limiting screen time before bed.' },
          { name: 'Mental recovery', sets: 0, reps: '0', rest: '0', illustration: '/mental.svg', instructions: 'Practice stress management techniques like meditation, deep breathing, or light reading. Mental recovery enhances physical recovery.' },
        ],
      },
    ];
  } else {
    // For maintenance and general fitness with full week day splits
    return [
      {
        title: 'Full Body Workout A',
        description: 'Balanced upper and lower body training',
        duration: '40 min',
        difficulty: 'intermediate',
        day: 'Monday',
        focus: 'Full Body',
        exercises: [
          { name: 'Goblet Squats', sets: 3, reps: '12 reps', rest: '60 sec', equipment: 'Dumbbell', illustration: '/goblet-squat.svg', instructions: 'Hold dumbbell vertically close to chest. Stand with feet slightly wider than shoulders, squat by pushing hips back and bending knees, then return to standing.' },
          { name: 'Push-ups', sets: 3, reps: '10-12 reps', rest: '45 sec', equipment: 'Bodyweight', illustration: '/push-up.svg', instructions: 'Start in plank position with hands slightly wider than shoulders. Lower your body until chest nearly touches the floor, then push back up. Keep body in straight line throughout.' },
          { name: 'Dumbbell rows', sets: 3, reps: '12 each arm', rest: '45 sec', equipment: 'Dumbbells/Bench', illustration: '/dumbbell-row.svg', instructions: 'Place one knee and hand on bench, other foot on floor. With dumbbell in free hand, pull weight up to side of chest, keeping elbow close to body, then lower.' },
          { name: 'Plank', sets: 3, reps: '30-45 sec', rest: '30 sec', equipment: 'Bodyweight', illustration: '/plank.svg', instructions: 'Position forearms on ground with elbows under shoulders, extend legs behind you. Create straight line from head to heels, engage core and hold position.' },
          { name: 'Jumping lunges', sets: 3, reps: '10 each leg', rest: '45 sec', equipment: 'Bodyweight', illustration: '/jumping-lunge.svg', instructions: 'Start in lunge position. Jump explosively upward, switching legs in mid-air to land with opposite leg forward. Continue alternating with each rep.' },
        ],
      },
      {
        title: 'Cardio & Core Circuit',
        description: 'Boost cardiovascular health and core strength',
        duration: '35 min',
        difficulty: 'intermediate',
        day: 'Tuesday',
        focus: 'Cardio/Core',
        exercises: [
          { name: 'Jump rope', sets: 3, reps: '60 sec', rest: '30 sec', equipment: 'Jump rope', illustration: '/jump-rope.svg', instructions: 'Jump with both feet together, keeping a steady rhythm. Stay on balls of feet with slight knee bend. Keep shoulders relaxed and wrists controlling rope movement.' },
          { name: 'Mountain climbers', sets: 3, reps: '45 sec', rest: '30 sec', equipment: 'Bodyweight', illustration: '/mountain-climbers.svg', instructions: 'Start in plank position. Rapidly alternate bringing knees toward chest as if running in place. Keep hips level and core engaged throughout.' },
          { name: 'Russian twists', sets: 3, reps: '15 each side', rest: '30 sec', equipment: 'Dumbbell/Medicine ball', illustration: '/russian-twist.svg', instructions: 'Sit with knees bent and feet elevated. Lean back slightly, rotate torso to tap weight on floor beside hip, then rotate to opposite side.' },
          { name: 'Burpees', sets: 3, reps: '10 reps', rest: '45 sec', equipment: 'Bodyweight', illustration: '/burpees.svg', instructions: 'Start standing, squat down placing hands on floor, jump feet back to plank, perform push-up, jump feet forward to squat, then jump up with hands overhead.' },
          { name: 'Plank shoulder taps', sets: 3, reps: '10 each side', rest: '45 sec', equipment: 'Bodyweight', illustration: '/shoulder-taps.svg', instructions: 'Start in high plank position. While maintaining stable hips, lift one hand to tap opposite shoulder, then return to floor. Alternate sides.' },
        ],
      },
      {
        title: 'Active Recovery',
        description: 'Light activity to enhance recovery and mobility',
        duration: '30 min',
        difficulty: 'beginner',
        day: 'Wednesday',
        focus: 'Recovery/Mobility',
        exercises: [
          { name: 'Light walking', sets: 1, reps: '10 min', rest: '0 min', illustration: '/walking.svg', instructions: 'Walk at comfortable pace with good posture. Focus on deep breathing and relaxing tight muscles.' },
          { name: 'Dynamic stretching', sets: 2, reps: '30 sec each movement', rest: '15 sec', illustration: '/dynamic-stretch.svg', instructions: 'Perform arm circles, leg swings, walking lunges, and torso rotations. Move through full range of motion without bouncing.' },
          { name: 'Foam rolling', sets: 1, reps: '45-60 sec per area', rest: '0 min', equipment: 'Foam Roller', illustration: '/foam-roll.svg', instructions: 'Roll slowly over major muscle groups, pausing on tight spots. Focus on quads, IT bands, hamstrings, calves, and upper back.' },
          { name: 'Cat-cow stretch', sets: 3, reps: '5-8 cycles', rest: '30 sec', illustration: '/cat-cow.svg', instructions: 'Start on hands and knees. Alternate between arching spine upward (cat) and allowing it to sag while lifting head (cow). Coordinate movement with breath.' },
          { name: 'World\'s greatest stretch', sets: 2, reps: '5 each side', rest: '30 sec', illustration: '/greatest-stretch.svg', instructions: 'From lunge position, place hand on inside of front foot, rotate torso upward with arm extended, then reach through with opposite arm. Flow through movement.' },
        ],
      },
      {
        title: 'Full Body Workout B',
        description: 'Alternative full-body training with different exercises',
        duration: '45 min',
        difficulty: 'intermediate',
        day: 'Thursday',
        focus: 'Full Body',
        exercises: [
          { name: 'Dumbbell Romanian Deadlift', sets: 3, reps: '12 reps', rest: '60 sec', equipment: 'Dumbbells', illustration: '/dumbbell-rdl.svg', instructions: 'Stand holding dumbbells in front of thighs. Hinge at hips while maintaining slight knee bend, lower weights along legs until stretch in hamstrings, then drive hips forward to return.' },
          { name: 'Dumbbell Bench Press', sets: 3, reps: '10 reps', rest: '60 sec', equipment: 'Dumbbells/Bench', illustration: '/dumbbell-bench.svg', instructions: 'Lie on bench holding dumbbells at chest level. Press weights upward until arms are extended, keeping weights aligned over shoulders, then lower with control.' },
          { name: 'Dumbbell Shoulder Press', sets: 3, reps: '10 reps', rest: '60 sec', equipment: 'Dumbbells', illustration: '/dumbbell-shoulder-press.svg', instructions: 'Sit or stand holding dumbbells at shoulder height. Press weights overhead until arms are almost fully extended (slight bend in elbows at top), then lower with control.' },
          { name: 'Bulgarian split squats', sets: 3, reps: '10 each leg', rest: '45 sec', equipment: 'Bench/Dumbbells', illustration: '/bulgarian-split-squat.svg', instructions: 'Stand with one foot on bench behind you. Lower by bending front knee until thigh is parallel to floor, keeping knee behind toe, then push through front heel to return.' },
          { name: 'Mountain climbers', sets: 3, reps: '30 sec', rest: '30 sec', equipment: 'Bodyweight', illustration: '/mountain-climbers.svg', instructions: 'Start in plank position with arms straight. Rapidly alternate bringing knees to chest, keeping your back flat and hips level throughout.' },
        ],
      },
      {
        title: 'Core & Mobility',
        description: 'Build core strength and improve flexibility',
        duration: '30 min',
        difficulty: 'intermediate',
        day: 'Friday',
        focus: 'Core/Mobility',
        exercises: [
          { name: 'Dead bugs', sets: 3, reps: '10 each side', rest: '30 sec', equipment: 'Bodyweight', illustration: '/dead-bug.svg', instructions: 'Lie on back with arms extended above chest and legs raised with 90° bend at knees. Lower opposite arm and leg toward floor while maintaining lower back contact, then return and alternate.' },
          { name: 'Glute bridges', sets: 3, reps: '15 reps', rest: '30 sec', equipment: 'Bodyweight', illustration: '/glute-bridge.svg', instructions: 'Lie on back with knees bent, feet flat on floor. Press through heels to lift hips toward ceiling until body forms straight line from shoulders to knees, then lower.' },
          { name: 'Bird dogs', sets: 3, reps: '8 each side', rest: '30 sec', equipment: 'Bodyweight', illustration: '/bird-dog.svg', instructions: 'Start on hands and knees. Simultaneously extend one arm forward and opposite leg backward until both are parallel to floor, then return and repeat on opposite side.' },
          { name: 'Side planks', sets: 2, reps: '30 sec each side', rest: '30 sec', equipment: 'Bodyweight', illustration: '/side-plank.svg', instructions: 'Lie on side with elbow under shoulder, forearm on ground. Stack feet or stagger them for stability. Lift hips to create straight line from head to feet, hold position.' },
          { name: 'Cat-cow stretch', sets: 2, reps: '10 reps', rest: '30 sec', equipment: 'Bodyweight', illustration: '/cat-cow.svg', instructions: 'Start on hands and knees. Arch back upward like cat while exhaling, then drop belly toward floor while lifting head and tailbone on inhale. Flow between positions.' },
        ],
      },
      {
        title: 'Outdoor Adventure',
        description: 'Take your workout outside for a change of scenery',
        duration: '45-60 min',
        difficulty: 'intermediate',
        day: 'Saturday',
        focus: 'Cardio/Fun',
        exercises: [
          { name: 'Trail walking/hiking', sets: 1, reps: '30-45 min', rest: '0 min', illustration: '/hiking.svg', instructions: 'Find a local trail or park. Walk/hike at moderate pace, enjoying nature while maintaining good posture and breathing deeply.' },
          { name: 'Park bench dips', sets: 3, reps: '12 reps', rest: '45 sec', equipment: 'Bench', illustration: '/bench-dips.svg', instructions: 'Sit on edge of park bench, hands gripping edge. Slide forward so rear is off bench, lower by bending elbows, then push back up.' },
          { name: 'Park bench step-ups', sets: 3, reps: '10 each leg', rest: '45 sec', equipment: 'Bench', illustration: '/step-up.svg', instructions: 'Stand facing park bench. Step one foot onto bench, press through heel to bring body up, then step back down. Complete all reps on one side before switching.' },
          { name: 'Tree push-ups', sets: 3, reps: '10 reps', rest: '45 sec', equipment: 'Tree', illustration: '/tree-pushup.svg', instructions: 'Find sturdy tree. Place hands on trunk at chest height, step back so body is angled. Perform push-ups by bending elbows, then straightening.' },
          { name: 'Outdoor cool down', sets: 1, reps: '5 min', rest: '0 min', illustration: '/outdoor-stretch.svg', instructions: 'Perform series of static stretches holding each for 20-30 seconds. Focus on major muscle groups used during workout.' },
        ],
      },
      {
        title: 'Sunday Active Recovery',
        description: 'Gentle movement to enhance recovery',
        duration: '25-30 min',
        difficulty: 'beginner',
        day: 'Sunday',
        focus: 'Recovery',
        exercises: [
          { name: 'Light cycling or walking', sets: 1, reps: '15 min', rest: '0 min', illustration: '/light-cardio.svg', instructions: 'Choose light cardio at conversational pace. Focus on enjoying movement rather than intensity.' },
          { name: 'Gentle yoga flow', sets: 1, reps: '10 min', rest: '0 min', illustration: '/yoga-flow.svg', instructions: 'Perform sequence of gentle yoga poses focusing on breath and movement. Include child\'s pose, downward dog, low lunges, and gentle twists.' },
          { name: 'Foam rolling', sets: 1, reps: '30-45 sec per area', rest: '0 min', equipment: 'Foam Roller', illustration: '/foam-roll.svg', instructions: 'Roll major muscle groups slowly, focusing on any tight areas. Include calves, hamstrings, quads, glutes, and upper back.' },
          { name: 'Joint mobility', sets: 1, reps: '8-10 reps per joint', rest: '0 min', illustration: '/joint-mobility.svg', instructions: 'Gently move each major joint through full range of motion. Include ankle circles, knee circles, hip circles, shoulder rolls, and neck rotations.' },
          { name: 'Mindful breathing', sets: 1, reps: '3-5 min', rest: '0 min', illustration: '/breathing.svg', instructions: 'Sit or lie comfortably. Focus on deep diaphragmatic breathing, extending exhales slightly longer than inhales. Pay attention to how body feels.' },
        ],
      },
    ];
  }
};
